services:
  - type: web
    name: youtube-downloader-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: youtube-downloader-api
          property: port
    disk:
      name: downloads
      mountPath: /opt/render/project/src/downloads
      sizeGB: 1
